### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by skyriakou** [commercetools/sunrise-spa#116]
Product Pagination - decide if we use 

- Load more
or 
- Pagination: 1,2,3
or
- both

**Comment by lauraluiz** [comment]
So far, write normal pagination with 75 product per page and with only option of going 1 page forward or backwards.

**Comment by lauraluiz** [comment]
Try to be clever and load 75 in computer, but less in smaller devices.

**Comment by lauraluiz** [comment]
Consider dropping products per page as calculating a smart amount of products per page might be enough, instead of letting the customer decide.
