### ISSUE TITLE
Consider using Apollo cache for local state

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/sunrise-spa#121]
Instead of using Vuex, Apollo Cache allows us to save and read local state.
https://dev.to/n_tepluhina/apollo-state-management-in-vue-application-8k0

Pros: get rid of any additional state management library such as Vuex and keeping only one state source.

Cons: Vuex is very well known and documented, whereas using Apollo for that is still quite obscure and difficult to find information of it.

**Comment by zeina-idris** [comment]
@lauraluiz  what about this issue? That we are actually using Vuex for local state

**Comment by lauraluiz** [comment]
Yep, I would drop this idea. Specially now that we will have it stored in the localstorage.
