### ISSUE TITLE
Fix UI after updating chrome

### ISSUE THREAD

**Issue by zeina-idris** [commercetools/sunrise-spa#155]
The UI broke after updating chrome to the latest version 77.0.3865.90 in the header and categories menu!
<img width="1280" alt="Screen Shot 2019-10-07 at 11 56 11" src="https://user-images.githubusercontent.com/31618523/66302626-8822e600-e8f9-11e9-8fb4-c26b56c1ad70.png">

**Comment by lauraluiz** [comment]
The problem is related to the icons, they are pushing the text down somehow.

**Comment by zeina-idris** [comment]
We are also facing this problem when opening categories menu!
![2019-10-11 13 06 22](https://user-images.githubusercontent.com/31618523/66647198-8b371280-ec28-11e9-9364-5e4b9a1f99dc.gif)
