### ISSUE TITLE
Insufficient scope

### ISSUE THREAD

**Issue by infmelon** [commercetools/sunrise-spa#168]
Following the instructions in the readme I get the following error when setting up with my own commercetools project. The store page also doesn't show any categories or products even though they're imported through sunrise-data.
![image](https://user-images.githubusercontent.com/53580783/70376391-e6277600-1908-11ea-8650-11d536d8de3d.png)

I tried adding the view_products scope on top of the "Mobile & SPA template" scopes, but the same error occurs.
Do the scopes in the template started deviating from the ones required for this project?

**Comment by amsterdamharu** [comment]
The work around for this is to create an api client in Merchant Center and after choosing the "Mobile & single-page application client" scope click on "Products (all)".
