### ISSUE TITLE
Token refresh for anonymous sessions

### ISSUE THREAD

**Issue by Jimtattersall** [commercetools/sunrise-spa#197]
Currently if a session has expired the token isn't refreshed. But rather a new one is just issued.

**Comment by harm-meijer** [comment]
@Jimtattersall Tried to use the refresh token but got into trouble when user logs in. Maybe give it another shot in the future but currently working on other implementations.

I tried [here](https://github.com/commercetools/sunrise-spa/blob/master/src/auth.js#L44) to check for a refresh token and use that but when a user tries to log in then apollo will call this function as well, this happens [here](https://github.com/commercetools/sunrise-spa/blob/master/src/auth.js#L20) and [here](https://github.com/commercetools/sunrise-spa/blob/master/src/apollo.js#L16).  The function getAuthToken is never called with parameters to indicate what is intended to happen and instead the tokenProvider is mutated before. 

I will try and simplify this by passing arguments to `tokenProvider` instead (there are only called in apollo twice and once in api). Then `getAuthToken` can decide how to mutate `tokenProvider` to do anonymous, token refresh or user login.

**Comment by harm-meijer** [comment]
Refresh token used [here](https://github.com/commercetools/sunrise-spa/blob/master/src/auth.js)
