### ISSUE TITLE
Response from an API extension is not visible in UI

### ISSUE THREAD

**Issue by harrykimpel** [commercetools/sunrise-spa#263]
I have created an API extension for the cart on create/update that checks the amount of line items in the cart. It does not allow more than 10 items in the cart (as an example). 

The issue is that the UI does not show the response of the API extension (success/failure).

![image](https://user-images.githubusercontent.com/2581608/132822584-cb8847d2-9b75-4f5f-b772-ba9db90e2a52.png)

**Comment by harm-meijer** [comment]
I will need to refactor [this code](https://github.com/commercetools/sunrise-spa/blob/fix-tests/src/composition/useCart.js#L31-L33) to use Apollo but the [old version](https://github.com/commercetools/sunrise-spa/blob/master/src/components/cartdetail/PageCartDetail/PageCartDetail.js#L28-L46) did not have error handling. The new version that will use composition with Apollo will have this.

If you need help to apply error handling in that page then please let me know (email). The problem with the old version is that cart has repeating code in several components so error handling for cart in the master branch has to be a duplicate implementation.
