### ISSUE TITLE
Set PLP image size for all breakpoints.

### ISSUE THREAD

**Issue by jluterek** [commercetools/sunrise-spa#265]
At large browser sizes the gallery has an unexpected display.  Suggest setting image size for PLP products or setting a max-width for the entire website.

https://demo.commercetools.com/DE/en/products/all/1?q=sweater

![sunrise](https://user-images.githubusercontent.com/17462045/136037815-af7c41da-e937-4c6a-bca1-871e860b6649.gif)

**Comment by harm-meijer** [comment]
I have fixed the style here: https://github.com/commercetools/sunrise-spa/pull/266 set max-height on the image
