### ISSUE TITLE
Following issues occurred after taking latest pull  

### ISSUE THREAD

**Issue by satyamh1** [commercetools/sunrise-spa#288]
ERROR  Failed to compile with 23 errors                                                                     
 error  in ./src/presentation/fashion/CartDetail/CartLikeContentDetail/LineItemInfo/LineItemInfo.vue?vue&type=template&id=a0f2a550

Module parse failed: Unexpected token (114:24)
File was processed with these loaders:
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/babel-loader/lib/index.js
 * ./node_modules/vue-loader-v16/dist/templateLoader.js
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/vue-loader-v16/dist/index.js
You may need an additional loader to handle the result of these loaders.
|   /* PROPS */
|   , ["price"]), _ctx.lineItem.price.discounted != null ? (_openBlock(), _createElementBlock("span", _hoisted_11, [_createVNode(_component_DiscountTag, {
>     name: _ctx.lineItem?.price?.discounted?.discount?.name
|   }, null, 8
|   /* PROPS */

**Comment by harm-meijer** [comment]
@satyamh1  Can you try to install with `yarn install --frozen-lockfile`?

**Comment by satyamh1** [comment]
@harm-meijer  Its working with "yarn install --frozen-lockfile" 

Thanks for quick help.
