### ISSUE TITLE
yarn install gives error for version 18 of nodejs

### ISSUE THREAD

**Issue by angrymrt** [commercetools/sunrise-spa#294]
When executing:
`yarn install`
You get the following error:
`expected node engine version 12 | 14 | 16 | 17, but got v18.8.0`

When you downgrade to nodejs version 17, the installation works.

**Comment by harm-meijer** [comment]
Vue will often break on minor updates you should use `yarn install --frozen-lockfile` as per the [documentation](https://github.com/commercetools/sunrise-spa/blob/master/README.md#start-guide).

You can try the following:

```
//restore original yarn.lock
git checkout f7a1b591b05d919cc59f1bbca05adf6095334fe8 yarn.lock
//install according to working minor version
yarn install --frozen-lockfile

```
