### ISSUE TITLE
How to integrate third party payment system like paypal plus or cybersource to sunrise via commercetools

### ISSUE THREAD

**Issue by amolbotre769** [commercetools/sunrise-spa#295]
I see documentation but I won't understand how to integrate. Any please can help me or shared resources. It will be helpful for me

**Comment by harm-meijer** [comment]
@amolbotre769 What are you trying to do?

**Comment by amolbotre769** [comment]
@harm-meijer I want to  do this https://github.com/commercetools/commercetools-paypal-plus-integration integration. I see the documentation but I don't understand how to do and what steps to follow.

**Comment by harm-meijer** [comment]
@amolbotre769 You can implement payment in [this page](https://github.com/commercetools/sunrise-spa/tree/master/src/presentation/fashion/Pay). Once you have a code from the payment provider you can use it [here](https://github.com/commercetools/sunrise-spa/blob/master/src/presentation/fashion/Pay/Pay.js#L20-L23). You can pass in a transaction id [here](https://github.com/commercetools/sunrise-spa/blob/master/composition/useCartMutation.js#L84), and save it [here](https://github.com/commercetools/sunrise-spa/blob/master/composition/ct/useCartMutation.js#L6).

**Comment by amolbotre769** [comment]
@harm-meijer thanks for the guide
