### ISSUE TITLE
How to call the external api

### ISSUE THREAD

**Issue by satyam21041997** [commercetools/sunrise-spa#301]
Hi,
I have to call the Get method API from Sunrise Application and have to use the response data into the application.
I am successfully able to fetch the data from Postman.
What will be the way to call the API from Sunrise Application?

**Comment by harm-meijer** [comment]
@satyam21041997 Assuming you followed the [start guide](https://github.com/commercetools/sunrise-spa/blob/master/README.md#start-guide), when you want to connect to your own commercetools project you have to [set up the environment](https://github.com/commercetools/sunrise-spa/tree/development/Docs#Environment-variables) and the correct [currency, countries and languages](https://github.com/commercetools/sunrise-spa/tree/development/Docs#Locale-and-Location)
