### ISSUE TITLE
Cannot Sign _in_ because password input requires five characters

### ISSUE THREAD

**Issue by nkuehn** [commercetools/sunrise-spa#34]
The new Sign-in  does not submit the sign-in when the password does not have at least five characters.   Eg.  a demo account with password "test" does not sign in. 

It's not the role of the sign-in  form to validate password strength requirements,  that is the role of the sign-_up_ form.

**Comment by lauraluiz** [comment]
Yep, you are right, but I wanted to test this vuelidate with more examples that just "required". I will remove it once we implement the sign up (so that we don't throw away the translations). This issue will remind us if we forget 😉

**Comment by lauraluiz** [comment]
Solved #44
