### ISSUE TITLE
Add "add to cart" button in Sunrise SPA  (TEST EPIC)

### ISSUE THREAD

**Issue by skyriakou** [commercetools/sunrise-spa#89]
### What
Users want a way of defining and inserting a product into the cart

### Why
So that they can buy the product

### Acceptance criteria

- [ ] Users can use a button on the PDP to add the specified product in the cart
- [ ] The specified product can be used in the cart and checkout process

**Comment by lauraluiz** [comment]
The test is not needed anymore
